language: php

php:
  - 7.0

env:
  - TYPO3_VERSION=^7.6 COVERAGE=0 FUNCTIONAL=0
  - TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

matrix:
  include:
    - php: 7.0
      env: TYPO3_VERSION=dev-master COVERAGE=1 FUNCTIONAL=1
  allow_failures:
    - env: TYPO3_VERSION=dev-master COVERAGE=0 FUNCTIONAL=0

notifications:
  email:
    recipients:
      - tomasnorre@gmail.com
    on_success: never
    on_failure: never

sudo: false

addons:
  apt:
    packages:
      - parallel

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer --version

before_script:
  # Installs TYPO3
  - composer require typo3/cms=$TYPO3_VERSION
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Restore composer.json
  - git checkout composer.json
  # Locating UnitTests.xml
  - export "UNIT_XML"=`find . -name 'UnitTests.xml' -type f`
  # Location FunctionalTests.xml
  - export "FUNCTIONAL_XML"=`find . -name 'FunctionalTests.xml' -type f`

script:
  - >
    echo;
    echo "Running php lint";
    find . -name \*.php ! -path "./.Build/*" ! -path "./scripts/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
  - >
    if [[ "$COVERAGE" == "0" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --colors  -c $UNIT_XML Tests/Unit/
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Running unit tests";
      .Build/bin/phpunit --coverage-clover=unittest-coverage.clover --colors -c $UNIT_XML Tests/Unit/
    fi
  - >
    if [[ "$FUNCTIONAL" == "1" ]]; then
      echo;
      echo "Running functional tests";
      export typo3DatabaseName="typo3";
      export typo3DatabaseHost="localhost";
      export typo3DatabaseUsername="root";
      export typo3DatabasePassword="";
      find 'Tests/Functional' -wholename '*Test.php' | parallel --gnu 'echo; echo "Running functional test suite {}"; .Build/bin/phpunit --coverage-clover={}functionaltest-coverage.clover --colors  -c $FUNCTIONAL_XML {}'
    fi
  - >
    if [[ "$COVERAGE" == "1" ]]; then
      echo;
      echo "Uploading code coverage results";
      wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover unittest-coverage.clover
      find 'Tests/Functional' -wholename '*Test.php' -exec php ocular.phar code-coverage:upload --format=php-clover {}functionaltest-coverage.clover \;
    fi